CREATE TABLE IF NOT EXISTS vehicleinfo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    vehiclenumber VARCHAR(20) NOT NULL UNIQUE,
    vehicletype VARCHAR(50) NOT NULL,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_vehicle (vehiclenumber)
);
